package com.example.springbooterp.dao;


import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

import javax.persistence.*;

@Entity
@Table(name = "employee")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description  = "All attributes of Employee Data")
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Setter(AccessLevel.NONE)
    @Schema(description = "AutoGeneratedId")
    private long id;

    private String firstName;

    private String lastName;

    @Schema(description = "Gmail Id")
    private String email;

    @Schema(hidden = true)
    private String password;

}
